# .streamlit/config.toml

[theme]
primaryColor="#f63366"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

[server]
headless = true
port = 7860
enableCORS = false
